In [13]:
import seaborn as se
import pandas as pd
import matplotlib

In [14]:
df = pd.read_csv("Student_Mental_health.csv")
df.tail()

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
197,24/07/2020 17:32:09,Female,20.0,Visual Arts,year 3,3.50 - 4.00,No,Yes,Yes,No,No
198,24/07/2020 17:34:01,Male,21.0,Graphic Design,Year 4,3.00 - 3.49,Yes,No,Yes,Yes,Yes
199,24/07/2020 17:36:25,Female,22.0,Fine Arts,year 3,3.50 - 4.00,Yes,Yes,Yes,Yes,No
200,15/10/2023 09:00,Female,24.0,Electrical Engineering,2nd Year,3.6,Single,No,Yes,Yes,Yes
201,15/10/2023 09:00,Female,24.0,Electrical Engineering,2nd Year,3.6,Single,No,Yes,Yes,Yes

In [ ]:
#Create new file and add new row for csv 
'''import csv

with open('Student_Mental_health.csv', 'w', newline='') as file:
    writer = csv.writer(file)

    writer.writerow(["25/07/2020 09:00", "Female", 24, "Electrical Engineering", "2nd Year", 3.6, "Single", "No", "Yes", "Yes", "Yes"])'''

In [12]:
#inserting elements to existing csv file 
#single row (writerow)
'''import csv

data_to_add =("15/10/2023 09:00", "Female", 24, "Electrical Engineering", "2nd Year", 3.6, "Single", "No", "Yes", "Yes", "Yes")

with open('Student_Mental_health.csv', 'a', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(data_to_add)'''

In [16]:
#inserting elements to existing csv file 
#multiple rows (writerow)
'''import csv

data_to_add = [
    ("16/10/2023 09:00", "Female", 24, "Electrical Engineering", "2nd Year", 3.6, "Single", "No", "Yes", "Yes", "Yes"),
    ("15/10/2023 09:00", "Female", 24, "Electrical Engineering", "2nd Year", 3.6, "Single", "No", "Yes", "Yes", "Yes")
]

with open('Student_Mental_health.csv', 'a', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data_to_add)'''

In [ ]:
#print the content in the csv files
'''import csv

with open("Student Mental health.csv", 'r') as file:
  csvreader = csv.reader(file)
  for row in csvreader:
    print(row)'''

In [17]:
df.columns

Index(['Timestamp', 'Choose your gender', 'Age', 'What is your course?',
       'Your current year of Study', 'What is your CGPA?', 'Marital status',
       'Do you have Depression?', 'Do you have Anxiety?',
       'Do you have Panic attack?',
       'Did you seek any specialist for a treatment?'],
      dtype='object')

In [18]:
df.head()

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No

In [ ]:
new_entries = [
    {
        "Timestamp": "15/10/2023 09:00",
        "Gender": "Female",
        "Age": 24,
        "Course": "Electrical Engineering",
        "Year of Study": "2nd Year",
        "CGPA": 3.6,
        "Marital Status": "Single",
        "Depression": "No",
        "Anxiety": "Yes",
        "Panic Attack": "Yes",
        "Specialist Treatment": "Yes"
    }
]


# Convert the new entries to a DataFrame
new_data = pd.DataFrame(new_entries)

# Concatenate the existing dataset with the new data
pd.concat([df, new_data], ignore_index=True)

# Print the updated dataset
#print(updated_data)

In [ ]:
import csv
import pandas as pd

# Read the existing CSV file into a DataFrame
df = pd.read_csv("Student_Mental_health.csv")

# Data to append
data_to_add = ["15/10/2023 09:00", "Female", 24, "Electrical Engineering", "2nd Year", 3.6, "Single", "No", "Yes", "Yes", "Yes"]

# Create a new DataFrame from the data to add
new_row = pd.DataFrame([data_to_add], columns=df.columns)

# Concatenate the original DataFrame and the new row
df = pd.concat([df, new_row], ignore_index=True)

# Write the updated DataFrame back to the CSV file
df.to_csv("Student_Mental_health.csv", index=False)